AWSTemplateFormatVersion: "2010-09-09"
Description: CodePipeline with Cloudformation 

Parameters:
  PipeLineName:
    Type: String
    Default: default-pipeline
  ConfigurationOwner:
    Type: String
    Default: Axit88
  Repo:
    Type: String
    Default: central-pipeline
  Branch:
    Type: String
    Default: main
  OAuthToken:
    Type: String
    Default: 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
  BucketName:
    Type: String
    Default: axitsamplepipelinebucket
  DeployStackName:
    Type: String
    Default: central-pipeline-stack
  CodePipelineRoleName: 
    Type: String
    Default: central-nested-codepipeline-role
  CodePipelinePolicyName: 
    Type: String
    Default: central-nested-codepipeline-policy
  CodePipelineRoleForDeploy:
    Type: String
    Default: central-nested-codepipeline-deploy-role
  BuildType: 
    Type: String
    Default: LINUX_CONTAINER
  BuildImage:
    Type: String
    Default: aws/codebuild/amazonlinux2-x86_64-standard:4.0
  BuildComputeType: 
    Type: String
    Default: BUILD_GENERAL1_SMALL
  IAMRoleForLambdaCodeBuildName:
    Type: String
    Default: central-nested-IAMRoleForCentralPipelineCodeBuild

Resources:
  IAMRoleForCodePipeline:
    Type: "AWS::IAM::Role"
    Properties:
      Path: "/"
      RoleName: !Ref CodePipelineRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "codepipeline.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Tags:
        - Key: env 
          Value: integration 
        - Key: application 
          Value: codepipeline 
  
  IAMRoleForDeployCodepipeline:
    Type: "AWS::IAM::Role"
    Properties:
      Path: "/"
      RoleName: !Ref CodePipelineRoleForDeploy
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "cloudformation.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
      - PolicyName: codeDeployPolicyForAppPipeline
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Action:
            - organizations:*
            - sso:*
            Resource: "*"
            Effect: Allow
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonS3FullAccess"

  IAMPolicyForCodePipeline:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Ref CodePipelinePolicyName
      PolicyDocument:
        Statement:
        - Action:
          - s3:GetObject
          - s3:GetObjectVersion
          - s3:GetBucketVersioning
          Resource: "*"
          Effect: Allow
        - Action:
          - s3:PutObject
          Resource:
          - arn:aws:s3:::codepipeline*
          - arn:aws:s3:::elasticbeanstalk*
          Effect: Allow
        - Action:
          - codecommit:CancelUploadArchive
          - codecommit:GetBranch
          - codecommit:GetCommit
          - codecommit:GetUploadArchiveStatus
          - codecommit:UploadArchive
          Resource: "*"
          Effect: Allow
        - Action:
          - codedeploy:CreateDeployment
          - codedeploy:GetApplicationRevision
          - codedeploy:GetDeployment
          - codedeploy:GetDeploymentConfig
          - codedeploy:RegisterApplicationRevision
          Resource: "*"
          Effect: Allow
        - Action:
          - elasticbeanstalk:*
          - ec2:*
          - elasticloadbalancing:*
          - autoscaling:*
          - cloudwatch:*
          - s3:*
          - sns:*
          - cloudformation:*
          - rds:*
          - sqs:*
          - ecs:*
          - iam:PassRole
          Resource: "*"
          Effect: Allow
        - Action:
          - lambda:InvokeFunction
          - lambda:ListFunctions
          Resource: "*"
          Effect: Allow
        - Action:
          - opsworks:CreateDeployment
          - opsworks:DescribeApps
          - opsworks:DescribeCommands
          - opsworks:DescribeDeployments
          - opsworks:DescribeInstances
          - opsworks:DescribeStacks
          - opsworks:UpdateApp
          - opsworks:UpdateStack
          Resource: "*"
          Effect: Allow
        - Action:
          - cloudformation:CreateStack
          - cloudformation:DeleteStack
          - cloudformation:DescribeStacks
          - cloudformation:UpdateStack
          - cloudformation:CreateChangeSet
          - cloudformation:DeleteChangeSet
          - cloudformation:DescribeChangeSet
          - cloudformation:ExecuteChangeSet
          - cloudformation:SetStackPolicy
          - cloudformation:ValidateTemplate
          - iam:PassRole
          Resource: "*"
          Effect: Allow
        - Action:
          - codebuild:BatchGetBuilds
          - codebuild:StartBuild
          Resource: "*"
          Effect: Allow
        Version: '2012-10-17'
      Roles:
        - Ref: IAMRoleForCodePipeline
      
  CentralCodePipeLine:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Type: S3
        Location: !Ref BucketName
      Name: !Ref PipeLineName
      RoleArn: !GetAtt IAMRoleForCodePipeline.Arn
      Stages:
        - Name: Source
          Actions:
            - Name: Source 
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: "1"
                Provider: GitHub
              Configuration:
                Owner: !Ref ConfigurationOwner
                Repo: !Ref Repo
                Branch: !Ref Branch
                OAuthToken: !Ref OAuthToken
                PollForSourceChanges: false
              OutputArtifacts:
                - Name: SourceOutput
              RunOrder: 1

        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: !Ref BuildProject
              RunOrder: 1

        - Name: Deploy
          Actions:
            - Name: Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: CloudFormation
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: !Ref DeployStackName
                Capabilities: CAPABILITY_NAMED_IAM
                TemplatePath: BuildOutput::rootStack.yaml
                RoleArn: !GetAtt IAMRoleForDeployCodepipeline.Arn
              InputArtifacts:
                - Name: BuildOutput
              RunOrder: 2
  
  BuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: CentralPipelineBuildProject
      Source:
        Type: GITHUB
        Location: !Sub 'https://github.com/${ConfigurationOwner}/${Repo}.git'
      Artifacts:
        Type: S3 
        Name: CentralBuildProjectArtifacts
        Location: !Ref BucketName
      # Triggers:
      #   Webhook: true
      Environment:
        Type: !Ref BuildType
        Image: !Ref BuildImage
        ComputeType: !Ref BuildComputeType
        ImagePullCredentialsType: CODEBUILD
      ServiceRole: !GetAtt IAMRoleForCentralPipelineCodeBuild.Arn
      TimeoutInMinutes: 60
      QueuedTimeoutInMinutes: 480
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
  
  IAMRoleForCentralPipelineCodeBuild:
    Type: "AWS::IAM::Role"
    Properties:
      Path: "/"
      RoleName: !Ref IAMRoleForLambdaCodeBuildName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "codebuild.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
        - "arn:aws:iam::aws:policy/CloudWatchLogsFullAccess"

Outputs:
  CentralCodePipeLine:
    Description: CentralCodePipeLine Detail
    Value: !Ref CentralCodePipeLine
    Export:
      Name: CentralCodePipeLine

# aws cloudformation create-stack --stack-name pipelineStack --template-body file://pipeline.yaml --capabilities CAPABILITY_NAMED_IAM --disable-rollback

# aws cloudformation update-stack --stack-name pipelineStack --template-body file://pipeline.yaml --capabilities CAPABILITY_NAMED_IAM --disable-rollback 
