AWSTemplateFormatVersion: "2010-09-09"
Description: Creating root stack, that will create nested stacks.

Parameters:
  BucketName:
    Type: String
    Default: axitsamplepipelinebucket

Resources:

  OUPolicyNestedStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${BucketName}.s3.${AWS::Region}.amazonaws.com/centralCloudformation/tagPolicy.yaml
      Parameters:
        OrganizationRoot: ou-3223-8wstomg3
  
  SsoPermissionSetNestedStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: OUPolicyNestedStack
    Properties:
      TemplateURL: !Sub https://${BucketName}.s3.${AWS::Region}.amazonaws.com/centralCloudformation/permissionSet.yaml
      Parameters:
        InstanceArn: arn:aws:sso:::instance/ssoins-77582076aa92fcf2
  
  SsoAssignPermissionSet:
    Type: AWS::CloudFormation::Stack
    DependsOn: SsoPermissionSetNestedStack
    Properties:
      TemplateURL: !Sub https://${BucketName}.s3.${AWS::Region}.amazonaws.com/centralCloudformation/assignment.yaml
      Parameters:
        AccountId: 540333447929
        InstanceArn: arn:aws:sso:::instance/ssoins-77582076aa92fcf2
        DevGroupId: c794aa38-f001-7066-07f6-bcf6929f5b3a
        QaGroupId: 27046a88-f0f1-7034-f086-f9b57b198317
        TechSupportGroupId: b7b4da38-d0a1-7081-028c-e6d29618801c
        DevopsGroupId: 37342a58-7091-7052-ed93-5f298e256777
  
  SnsNestedStack: 
    Type: AWS::CloudFormation::Stack
    DependsOn: OUPolicyNestedStack
    Properties:
      TemplateURL: !Sub https://${BucketName}.s3.${AWS::Region}.amazonaws.com/centralCloudformation/sns.yaml
      Parameters:
        SnsTopicName: default-sns-topic
        SnsEndPoint: axitdhola888@gmail.com
  
# aws cloudformation create-stack --stack-name CentralPipeline --template-body file://rootStack.yaml --capabilities CAPABILITY_NAMED_IAM --disable-rollback

# aws cloudformation update-stack --stack-name CentralPipeline --template-body file://rootStack.yaml --capabilities CAPABILITY_NAMED_IAM --disable-rollback 