AWSTemplateFormatVersion: '2010-09-09'
Description: Attach permission set to sso user and group

Parameters:
  AccountId: 
    Type: String
    Default: 540333447929

  InstanceArn:
    Type: String
    Default: arn:aws:sso:::instance/ssoins-77582076aa92fcf2
  
  DevGroupId: 
    Type: String
    Default: c794aa38-f001-7066-07f6-bcf6929f5b3a
  
  QaGroupId: 
    Type: String
    Default: 17846a18-e0c1-708f-5a78-abe68be0bca5

  TechSuppotGroupId: 
    Type: String
    Default: b7b4da38-d0a1-7081-028c-e6d29618801c
  
  DevopsroupId: 
    Type: String
    Default: 27046a88-f0f1-7034-f086-f9b57b198317

Resources:
 
  DevAssignment:
    Type: AWS::SSO::Assignment
    Properties:
      InstanceArn: !Ref InstanceArn
      PrincipalId: !Ref DevGroupId
      PrincipalType: GROUP 
      TargetId: !Ref AccountId
      TargetType: AWS_ACCOUNT
      PermissionSetArn: !ImportValue DevPermissionSet  
  
  QaAssignment:
    Type: AWS::SSO::Assignment
    Properties:
      InstanceArn: !Ref InstanceArn
      PrincipalId: !Ref QaGroupId
      PrincipalType: GROUP 
      TargetId: !Ref AccountId
      TargetType: AWS_ACCOUNT
      PermissionSetArn: !ImportValue QaPermissionSet  

  TechSupportAssignment:
    Type: AWS::SSO::Assignment
    Properties:
      InstanceArn: !Ref InstanceArn
      PrincipalId: !Ref TechSupportGroupId
      PrincipalType: GROUP 
      TargetId: !Ref AccountId
      TargetType: AWS_ACCOUNT
      PermissionSetArn: !ImportValue TechSupportPermissionSet  
  
  DevopsAssignment:
    Type: AWS::SSO::Assignment
    Properties:
      InstanceArn: !Ref InstanceArn
      PrincipalId: !Ref DevopsGroupId
      PrincipalType: GROUP 
      TargetId: !Ref AccountId
      TargetType: AWS_ACCOUNT
      PermissionSetArn: !ImportValue DevopsPermissionSet  

# aws cloudformation create-stack --stack-name SsoStack2 --template-body file://assignment.yaml --capabilities CAPABILITY_NAMED_IAM --disable-rollback

# aws cloudformation update-stack --stack-name SsoStack2 --template-body file://assignment.yaml --capabilities CAPABILITY_NAMED_IAM --disable-rollback 
